version: '3.3'

services:
  web:
    image: app.py
    ports:
     - "8000:80"

  words:
    image: app.py
    deploy:
      replicas: 5
      endpoint_mode: dnsrr
      resources:
        limits:
          memory: 50M
        reservations:
          memory: 50M

  db:
    image: app.py
